import { createSupabaseMiddlewareClient } from '@/utils/supabase/server';
import { type NextRequest, NextResponse } from 'next/server';

const publicRoutes = new Set([
    '/',
    '/login',
    '/unauthorized',
    '/privacy-policy',
    '/terms',
]);

function isPublicRoute(pathname: string) {
    return pathname.startsWith('/auth/') || publicRoutes.has(pathname);
}

/**
 * Helper function to redirect the user to a different page while ensuring that
 * any cookies set during the middleware execution (like Supabase auth tokens)
 * are carried over to the redirect response.
 *
 * @param request - NextRequest represents the incoming HTTP request. 
 *                  It contains details like the URL the user is trying to visit, 
 *                  incoming cookies, headers, and the user's IP address.
 * @param response - NextResponse represents the outgoing HTTP response we are building. 
 *                   In this middleware, Supabase might have already attached new 
 *                   authentication cookies to this response object.
 * @param pathname - The path we want to send the user to (e.g., "/login" or "/").
 */
function redirectWithCookies(
    request: NextRequest,
    response: NextResponse,
    pathname: string
) {
    // 1. Create a new URL based on where the user was trying to go, 
    // but change the path to our target destination (e.g., /login)
    const redirectUrl = request.nextUrl.clone();
    redirectUrl.pathname = pathname;
    redirectUrl.search = ''; // Clear any query parameters like ?id=123

    // 2. Create the actual redirect response telling the browser to go to the new URL
    const redirectResponse = NextResponse.redirect(redirectUrl);

    // 3. CRITICAL STEP: Copy all cookies from our original pending 'response' 
    // over to our new 'redirectResponse'. If we don't do this, the user might 
    // lose their freshly refreshed login session during the redirect!
    response.cookies.getAll().forEach((cookie) => {
        redirectResponse.cookies.set(cookie);
    });

    return redirectResponse;
}

export async function proxy(request: NextRequest) {
    // Middleware is the first auth checkpoint.
    // It keeps signed-out users away from protected pages before the UI loads.
    const { supabase, getResponse } = createSupabaseMiddlewareClient(request);
    const pathname = request.nextUrl.pathname;

    if (/\.[^/]+$/.test(pathname)) {
        return NextResponse.next();
    }

    const {
        data: { user },
    } = await supabase.auth.getUser();
    const response = getResponse();

    // Redirects user to /login when the user isn't valid AND the route isn't public
    if (!user && !isPublicRoute(pathname)) {
        return redirectWithCookies(request, response, '/login');
    }

    // User is validated and path is /login so take user to the dashboard
    if (user && pathname === '/login') {
        return redirectWithCookies(request, response, '/dashboard');
    }

    return response;
}

/**
 * The config object tells Next.js exactly WHICH routes should trigger this middleware.
 * If a route doesn't match this pattern, the middleware is completely skipped, saving server resources.
 */
export const config = {
    // The matcher uses a negative lookahead regular expression: `(?!...)`
    // It basically says: "Run this middleware on ALL routes ('/'), EXCEPT for the ones listed here:"
    // - api: API routes (like /api/hello)
    // - _next/static: Static files generated by Next.js (like CSS, JS bundles)
    // - _next/image: Optimized images generated by Next.js
    // - favicon.ico: The website's small icon in the browser tab
    matcher: ['/((?!api|_next/static|_next/image|favicon.ico).*)'],
};
